Remove 2.6.32 and 2.6.38 branches
linuxwacom/input-wacom pull request #239
Opened 2021-02-18 19:15 UTC by Pinglinux

RHEL 6 was EOL last year, which was based on 2.6.32. Plus most Linux
distributions do not support 2.6.38 any more.

Signed-off-by: Ping Cheng <ping.cheng@wacom.com>

2021-02-23 17:28 UTC, jigpu requested changes
A couple minor nitpicks.

Also, just for future reference, here are a few of the other impacted distros (all of which are EOL):

| Distro | Kernel | EOL |
|-|-|-|
| Debian 7 | 3.2 | 2018-06-01 |
| RHEL 6 | 2.6.32 | 2020-11-30 |
| SuSE Linux Enterprise 11.3 | 3.0 | 2016-01-31 |
| SuSE Linux Enterprise 11.4 | 3.0 | 2019-05-31 |
| Ubuntu 12.04 ("Precise Pangolin") | 3.2 | 2017-04-28 |

2021-02-23 17:28 UTC, jigpu commented on configure.ac
> +	[0.48.0])
The version number should only be updated when we make a release.

2021-02-23 17:28 UTC, jigpu commented on configure.ac
> +	AC_MSG_ERROR([Please use the kernel driver included in the 'linuxwacom' package for kernels older than 2.6.32])
We should remove this check and error message. The error message below for kernels older than 3.7 is sufficient.

2021-02-23 17:28 UTC, jigpu commented on configure.ac
> +	AC_MSG_ERROR(m4_normalize([Kernels older than 3.7 is no longer supported by input-wacom.
"is" -> "are"

2021-02-23 17:28 UTC, jigpu commented on .github/workflows/main.yml
> +        kernel: ["4.6", "4.5", "4.1", "3.19", "3.18", "3.17", "3.7"]
Please merge this entire commit with the previous one.

2021-02-23 17:28 UTC, jigpu commented on .github/workflows/main.yml
> +          SERIES=v$(awk -vFS=. -vOFS=. '{$2="x"; print}' <<< ${KERNELVER})
We could leave `NF=2` here just to be safe, but I'll leave that decision up to you.

2021-02-24 03:32 UTC, Pinglinux commented
> A couple minor nitpicks.
> 
> Also, just for future reference, here are a few of the other impacted distros (all of which are EOL):
> 
> Distro	Kernel	EOL
> Debian 7	3.2	2018-06-01
> RHEL 6	2.6.32	2020-11-30
> SuSE Linux Enterprise 11.3	3.0	2016-01-31
> SuSE Linux Enterprise 11.4	3.0	2019-05-31
> Ubuntu 12.04 ("Precise Pangolin")	3.2	2017-04-28

Thank you. I'll add this info to the commit comments.

2021-02-25 01:50 UTC, Pinglinux commented on configure.ac
> +	AC_MSG_ERROR([Please use the kernel driver included in the 'linuxwacom' package for kernels older than 2.6.32])
We can't remove the last line. It is still true that kernels older than 2.6.32 are supported by the old all-in-one linuxwacom package

2021-02-25 01:53 UTC, Pinglinux commented on configure.ac
> +	AC_MSG_ERROR([Please use the kernel driver included in the 'linuxwacom' package for kernels older than 2.6.32])
Well, probably no one cares about those old kernels anyway. I'll remove the message

2021-03-11 21:44 UTC, jigpu commented
Thanks Ping; the changes look good :+1: Feel free to merge the changes now.

2021-03-11 21:53 UTC, merged