chore: Set permissions for GitHub actions
linuxwacom/input-wacom pull request #317
Opened 2022-05-20 19:28 UTC by neilnaveen

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.

- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions

https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)

Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>

2022-07-05 21:55 UTC, Pinglinux commented
@jigpu Does it make sense to you?

2022-11-22 22:50 UTC, whot commented on .github/workflows/main.yml
> +  contents: read
after a quick skim of the github docs (thanks for the links!), I'm wondering - wouldn't 
```yaml
permissions: read-all
```
be better here? our CI doesn't need to write to anywhere.

2023-06-08 18:14 UTC, jigpu commented on .github/workflows/main.yml
> +  contents: read
I believe the patch as written is more restrictive than 'read-all' according to this line in the documentation:

> If you specify the access for any of these scopes, all of those that are not specified are set to none.

2023-06-08 18:22 UTC, jigpu requested changes
I'm happy with this change, though I'd like to see similar changes made to the other two workflows. I suspect the checkpatch workflow can have this same permission set, while the tagged-release workflow likely needs `contents: write` instead.

2023-11-29 22:56 UTC, jigpu commented
Closing in favor of #400 which makes the requested modifications.

2023-11-29 22:56 UTC, closed without merging